import React from "react";
import Sidebar from "./_components/Sidebar";

export const metadata = {
  title: "Profile",
  description: "Generated by create mazaharul islam",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body >
        <div className="flex gap-4">
           <div className="shadow-xl bg-gray-800 text-gray-300 font-semibold h-[100vh] ">
           <Sidebar />
           </div>
         {children}
        </div>
      </body>
    </html>
  );
}
