export const productList=[
    {
        name:"Apel",
        price:150,
        quentity:10,
        quentityType:"kG"
    },
    {
        name:"Angur",
        price:150,
        quentity:10,
        quentityType:"GM"
    },
    {
        name:"Kola",
        price:150,
        quentity:10,
        quentityType:"LETTER"
    },
    {
        name:"Begubn",
        price:150,
        quentity:10,
        quentityType:"POUND"
    },
    {
        name:"Banana",
        price:150,
        quentity:10,
        quentityType:"ML"
    },
    {
        name:"Coka cola",
        price:150,
        quentity:10,
        quentityType:"PICES"
    },
    {
        name:"Dim",
        price:150,
        quentity:10,
        quentityType:"TON"
    },
]